#/etc/bind/named.conf
#main config
options {
    directory "/var/bind";
    listen-on { 10.1.64.3; };
    allow-query {
        10.1.32.0/19;
        10.1.64.0/19;
        10.1.96.0/19;
        10.2.32.0/19;
        10.2.64.0/19;
        10.2.96.0/19;
    };
    allow-recursion {
        10.1.32.0/19;
        10.1.64.0/19;
        10.1.96.0/19;
        10.2.32.0/19;
        10.2.64.0/19;
        10.2.96.0/19;
    };
    forwarders { 8.8.8.8; };
    recursion yes;
};

zone "hq.local" IN {
    type master;
    file "/etc/bind/zones/db.hq.local";
};

zone "branch1.local" IN {
    type master;
    file "/etc/bind/zones/db.branch1.local";
};

zone "1.10.in-addr.arpa" IN {
    type master;
    file "/etc/bind/zones/db.10.1";
};

zone "2.10.in-addr.arpa" IN {
    type master;
    file "/etc/bind/zones/db.10.2";
};