#/etc/dnsmasq.conf
interface=eth0
bind-interfaces
dhcp-authoritative
no-resolv
server=10.1.64.3
log-queries
log-dhcp

#Static reservations
dhcp-host=02:42:bd:52:76:00,dhcp-server,10.1.64.2,infinite
dhcp-host=02:42:65:f2:93:00,ftp-server,10.1.64.4,infinite
dhcp-host=02:42:fe:ac:cb:00,db-server,10.1.32.2,infinite
dhcp-host=02:42:40:b6:05:00,dns-server,10.1.64.3,infinite

#VLAN 3 - Admin PCs
dhcp-range=set:vlan3,10.1.96.2,10.1.96.254,255.255.224.0,24h
dhcp-option=tag:vlan3,option:router,10.1.96.1
dhcp-option=tag:vlan3,option:dns-server,10.1.64.3

#VLAN 4 - Employee PCs
dhcp-range=set:vlan4,10.2.32.2,10.2.32.254,255.255.224.0,24h
dhcp-option=tag:vlan4,option:router,10.2.32.1
dhcp-option=tag:vlan4,option:dns-server,10.1.64.3

#VLAN 5 - ATM 1
dhcp-range=set:vlan5,10.2.64.2,10.2.64.254,255.255.224.0,24h
dhcp-option=tag:vlan5,option:router,10.2.64.1
dhcp-option=tag:vlan5,option:dns-server,10.1.64.3

#VLAN 6 - ATM 2
dhcp-range=set:vlan6,10.2.96.2,10.2.96.254,255.255.224.0,24h
dhcp-option=tag:vlan6,option:router,10.2.96.1
dhcp-option=tag:vlan6,option:dns-server,10.1.64.3